# Generated by Django 2.2.13 on 2021-02-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_auto_20210209_1003'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='xyz', max_length=15, unique=True),
        ),
    ]
