# Generated by Django 2.2.13 on 2021-04-07 12:07

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0004_auto_20210222_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, size=None)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connect',
            },
        ),
    ]
