# Generated by Django 2.2.13 on 2021-04-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0005_connecteduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connecteduser',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
