# Generated by Django 2.2.13 on 2021-04-08 10:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0006_auto_20210407_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connecteduser',
            name='people',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=None),
        ),
    ]
